// Định nghĩa roles và permissions theo database thực tế
export const ROLES = {
    WAREHOUSE_MANAGER: 'Warehouse Manager',
    WAREHOUSE_STAFF: 'Warehouse Staff',
    ADMINISTRATOR: 'Administrator',
    BUSINESS_OWNER: 'Business Owner',
    SALES_REPRESENTATIVE: 'Sales Representative',
    SALE_MANAGER: 'Sale Manager'
};

export const PERMISSIONS = {
    // Goods permissions
    GOODS_VIEW: 'Goods.View',
    GOODS_CREATE: 'Goods.Create',
    GOODS_UPDATE: 'Goods.Update',
    GOODS_DELETE: 'Goods.Delete',

    // Category permissions
    CATEGORY_VIEW: 'Category.View',
    CATEGORY_CREATE: 'Category.Create',
    CATEGORY_UPDATE: 'Category.Update',
    CATEGORY_DELETE: 'Category.Delete',

    // Supplier permissions
    SUPPLIER_VIEW: 'Supplier.View',
    SUPPLIER_CREATE: 'Supplier.Create',
    SUPPLIER_UPDATE: 'Supplier.Update',
    SUPPLIER_DELETE: 'Supplier.Delete',

    // Retailer permissions  
    RETAILER_VIEW: 'Retailer.View',
    RETAILER_CREATE: 'Retailer.Create',
    RETAILER_UPDATE: 'Retailer.Update',
    RETAILER_DELETE: 'Retailer.Delete',

    // Unit Measure permissions
    UNIT_MEASURE_VIEW: 'UnitMeasure.View',
    UNIT_MEASURE_CREATE: 'UnitMeasure.Create',
    UNIT_MEASURE_UPDATE: 'UnitMeasure.Update',
    UNIT_MEASURE_DELETE: 'UnitMeasure.Delete',

    // Area permissions
    AREA_VIEW: 'Area.View',
    AREA_CREATE: 'Area.Create',
    AREA_UPDATE: 'Area.Update',
    AREA_DELETE: 'Area.Delete',

    // Location permissions
    LOCATION_VIEW: 'Location.View',
    LOCATION_CREATE: 'Location.Create',
    LOCATION_UPDATE: 'Location.Update',
    LOCATION_DELETE: 'Location.Delete',
    LOCATION_PRINT: 'Location.Print',


    // Storage Condition permissions
    STORAGE_CONDITION_VIEW: 'StorageCondition.View',
    STORAGE_CONDITION_CREATE: 'StorageCondition.Create',
    STORAGE_CONDITION_UPDATE: 'StorageCondition.Update',
    STORAGE_CONDITION_DELETE: 'StorageCondition.Delete',

    // Batch permissions
    BATCH_VIEW: 'Batch.View',
    BATCH_CREATE: 'Batch.Create',
    BATCH_UPDATE: 'Batch.Update',
    BATCH_DELETE: 'Batch.Delete',

    // Account permissions
    ACCOUNT_VIEW: 'Account.View',
    ACCOUNT_CREATE: 'Account.Create',
    ACCOUNT_UPDATE: 'Account.Update',
    ACCOUNT_DELETE: 'Account.Delete',

    // Profile permissions
    PROFILE_VIEW: 'Profile.View',
    PROFILE_CHANGE_PASSWORD: 'Profile.ChangePassword',

    // Report permissions
    REPORT_VIEW: 'Report.View',
    REPORT_EXPORT: 'Report.Export',

    // Settings permissions
    SETTINGS_VIEW: 'Settings.View',
    SETTINGS_UPDATE: 'Settings.Update',

    // Dashboard permissions
    DASHBOARD_VIEW: 'Dashboard.View',
    ADMIN_DASHBOARD_VIEW: 'AdminDashboard.View',

    // Purchase Order permissions
    PURCHASE_ORDER_VIEW: 'PurchaseOrder.View',
    PURCHASE_ORDER_VIEW_RS: 'PurchaseOrder.ViewListRS',
    PURCHASE_ORDER_VIEW_SM: 'PurchaseOrder.ViewListSM',
    PURCHASE_ORDER_VIEW_WM: 'PurchaseOrder.ViewListWM',
    PURCHASE_ORDER_VIEW_WS: 'PurchaseOrder.ViewListWS',
    PURCHASE_ORDER_CREATE: 'PurchaseOrder.Create',
    PURCHASE_ORDER_UPDATE: 'PurchaseOrder.Update',
    PURCHASE_ORDER_DELETE: 'PurchaseOrder.Delete',
    PURCHASE_ORDER_VIEW_DETAILS: 'PurchaseOrder.ViewDetails',
    PURCHASE_ORDER_SUBMIT_REQUEST: 'PurchaseOrder.SubmitRequest',
    PURCHASE_ORDER_APPROVAL_REQUEST: 'PurchaseOrder.ApprovalRequest',
    PURCHASE_ORDER_CONFIRM_DELIVERY: 'PurchaseOrder.ConfirmDelivery',
    PURCHASE_ORDER_ASSIGN_RECEIVING: 'PurchaseOrder.AssignReceiving',

    // Kệ Kê Hàng permissions
    PALLET_VIEW: 'Pallet.View',
    PALLET_CREATE: 'Pallet.Create',
    PALLET_UPDATE: 'Pallet.Update',
    PALLET_DELETE: 'Pallet.Delete',
    PALLET_VIEW_DETAILS: 'Pallet.ViewDetails',
    PALLET_UPDATE_STATUS: 'Pallet.UpdateStatus',
    PALLET_PRINT_BARCODE: 'Pallet.PrintBarcode',
    PALLET_SCAN_BARCODE: 'Pallet.ScanBarcode',
    PALLET_VIEW_SUGGESTED_LOCATIONS: 'Pallet.ViewSuggestedLocations',
    PALLET_CONFIRM_INBOUND_PUTAWAY: 'Pallet.ConfirmInboundPutaway'


};

export const ROLE_PERMISSIONS = {
    [ROLES.ADMINISTRATOR]: [
        PERMISSIONS.ACCOUNT_VIEW, PERMISSIONS.ACCOUNT_CREATE, PERMISSIONS.ACCOUNT_UPDATE, PERMISSIONS.ACCOUNT_DELETE,
        PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.ADMIN_DASHBOARD_VIEW,
        PERMISSIONS.AREA_VIEW, PERMISSIONS.AREA_CREATE, PERMISSIONS.AREA_UPDATE, PERMISSIONS.AREA_DELETE,
        PERMISSIONS.LOCATION_VIEW, PERMISSIONS.LOCATION_CREATE, PERMISSIONS.LOCATION_UPDATE, PERMISSIONS.LOCATION_DELETE,
        PERMISSIONS.STORAGE_CONDITION_VIEW, PERMISSIONS.STORAGE_CONDITION_CREATE, PERMISSIONS.STORAGE_CONDITION_UPDATE, PERMISSIONS.STORAGE_CONDITION_DELETE,
        PERMISSIONS.REPORT_VIEW, PERMISSIONS.REPORT_EXPORT
    ],

    [ROLES.BUSINESS_OWNER]: [
        PERMISSIONS.ACCOUNT_VIEW, PERMISSIONS.ACCOUNT_CREATE, PERMISSIONS.ACCOUNT_UPDATE, PERMISSIONS.ACCOUNT_DELETE,
        PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.ADMIN_DASHBOARD_VIEW,
        PERMISSIONS.AREA_VIEW, PERMISSIONS.AREA_CREATE, PERMISSIONS.AREA_UPDATE, PERMISSIONS.AREA_DELETE,
        PERMISSIONS.LOCATION_VIEW, PERMISSIONS.LOCATION_CREATE, PERMISSIONS.LOCATION_UPDATE, PERMISSIONS.LOCATION_DELETE,
        PERMISSIONS.STORAGE_CONDITION_VIEW, PERMISSIONS.STORAGE_CONDITION_CREATE, PERMISSIONS.STORAGE_CONDITION_UPDATE, PERMISSIONS.STORAGE_CONDITION_DELETE,
        PERMISSIONS.REPORT_VIEW, PERMISSIONS.REPORT_EXPORT
    ],

    [ROLES.SALE_MANAGER]: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.GOODS_VIEW, PERMISSIONS.GOODS_CREATE, PERMISSIONS.GOODS_UPDATE, PERMISSIONS.GOODS_DELETE,
        PERMISSIONS.CATEGORY_VIEW, PERMISSIONS.CATEGORY_CREATE, PERMISSIONS.CATEGORY_UPDATE, PERMISSIONS.CATEGORY_DELETE,
        PERMISSIONS.UNIT_MEASURE_VIEW, PERMISSIONS.UNIT_MEASURE_CREATE, PERMISSIONS.UNIT_MEASURE_UPDATE, PERMISSIONS.UNIT_MEASURE_DELETE,
        PERMISSIONS.SUPPLIER_VIEW, PERMISSIONS.SUPPLIER_CREATE, PERMISSIONS.SUPPLIER_UPDATE, PERMISSIONS.SUPPLIER_DELETE,
        PERMISSIONS.RETAILER_VIEW, PERMISSIONS.RETAILER_CREATE, PERMISSIONS.RETAILER_UPDATE, PERMISSIONS.RETAILER_DELETE,
        PERMISSIONS.PURCHASE_ORDER_VIEW, PERMISSIONS.PURCHASE_ORDER_VIEW_SM, PERMISSIONS.PURCHASE_ORDER_VIEW_DETAILS, PERMISSIONS.PURCHASE_ORDER_APPROVAL_REQUEST,
        PERMISSIONS.REPORT_VIEW, PERMISSIONS.REPORT_EXPORT
    ],

    [ROLES.SALES_REPRESENTATIVE]: [
        PERMISSIONS.GOODS_VIEW,
        PERMISSIONS.SUPPLIER_VIEW,
        PERMISSIONS.RETAILER_VIEW,
        PERMISSIONS.PURCHASE_ORDER_VIEW, PERMISSIONS.PURCHASE_ORDER_VIEW_RS, PERMISSIONS.PURCHASE_ORDER_CREATE, PERMISSIONS.PURCHASE_ORDER_UPDATE, PERMISSIONS.PURCHASE_ORDER_DELETE, PERMISSIONS.PURCHASE_ORDER_VIEW_DETAILS,
        PERMISSIONS.PURCHASE_ORDER_SUBMIT_REQUEST,
        PERMISSIONS.REPORT_VIEW
    ],

    [ROLES.WAREHOUSE_MANAGER]: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.AREA_VIEW,
        PERMISSIONS.LOCATION_VIEW,
        PERMISSIONS.BATCH_VIEW, PERMISSIONS.BATCH_CREATE, PERMISSIONS.BATCH_UPDATE, PERMISSIONS.BATCH_DELETE,
        PERMISSIONS.PURCHASE_ORDER_VIEW, PERMISSIONS.PURCHASE_ORDER_VIEW_WM, PERMISSIONS.PURCHASE_ORDER_VIEW_DETAILS,
        PERMISSIONS.PURCHASE_ORDER_CONFIRM_DELIVERY, PERMISSIONS.PURCHASE_ORDER_ASSIGN_RECEIVING,
        PERMISSIONS.PALLET_VIEW, PERMISSIONS.PALLET_VIEW_DETAILS,
        PERMISSIONS.PALLET_PRINT_BARCODE, PERMISSIONS.PALLET_SCAN_BARCODE, PERMISSIONS.PALLET_VIEW_SUGGESTED_LOCATIONS,
        PERMISSIONS.REPORT_VIEW, PERMISSIONS.REPORT_EXPORT
    ],

    [ROLES.WAREHOUSE_STAFF]: [
        PERMISSIONS.AREA_VIEW,
        PERMISSIONS.LOCATION_VIEW, PERMISSIONS.LOCATION_PRINT,
        PERMISSIONS.BATCH_VIEW,
        PERMISSIONS.PURCHASE_ORDER_VIEW, PERMISSIONS.PURCHASE_ORDER_VIEW_WS, PERMISSIONS.PURCHASE_ORDER_VIEW_DETAILS,
        PERMISSIONS.PALLET_VIEW, PERMISSIONS.PALLET_CREATE, PERMISSIONS.PALLET_UPDATE, PERMISSIONS.PALLET_DELETE,
        PERMISSIONS.PALLET_VIEW_DETAILS, PERMISSIONS.PALLET_UPDATE_STATUS, PERMISSIONS.PALLET_PRINT_BARCODE,
        PERMISSIONS.PALLET_SCAN_BARCODE, PERMISSIONS.PALLET_VIEW_SUGGESTED_LOCATIONS, PERMISSIONS.PALLET_CONFIRM_INBOUND_PUTAWAY,
        PERMISSIONS.REPORT_VIEW
    ]
};
