// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class Area
{
    public int AreaId { get; set; }

    public string AreaName { get; set; }

    public string AreaCode { get; set; }

    public string Description { get; set; }

    public int StorageConditionId { get; set; }

    public int? Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual ICollection<Location> Locations { get; set; } = new List<Location>();

    public virtual ICollection<StocktakingArea> StocktakingAreas { get; set; } = new List<StocktakingArea>();

    public virtual StorageCondition StorageCondition { get; set; }
}