// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class BackOrder
{
    public Guid BackOrderId { get; set; }

    public int? RetailerId { get; set; }

    public int? GoodsId { get; set; }

    public int? GoodsPackingId { get; set; }

    public int? PackageQuantity { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public int? Status { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual Good Goods { get; set; }

    public virtual GoodsPacking GoodsPacking { get; set; }

    public virtual Retailer Retailer { get; set; }
}