// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class Batch
{
    public Guid BatchId { get; set; }

    public string BatchCode { get; set; }

    public int? GoodsId { get; set; }

    public DateOnly? ManufacturingDate { get; set; }

    public string Description { get; set; }

    public DateOnly? ExpiryDate { get; set; }

    public DateTime? CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public int? CreateBy { get; set; }

    public int? Status { get; set; }

    public virtual User CreateByNavigation { get; set; }

    public virtual Good Goods { get; set; }

    public virtual ICollection<Pallet> Pallets { get; set; } = new List<Pallet>();
}