// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class DisposalRequest
{
    public Guid DisposalRequestId { get; set; }

    public DateOnly? EstimatedTimeDeparture { get; set; }

    public int? Status { get; set; }

    public int? CreatedBy { get; set; }

    public int? ApprovalBy { get; set; }

    public int? AssignTo { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public DateTime? ApprovalAt { get; set; }

    public DateTime? AssignAt { get; set; }

    public string Note { get; set; }

    public string RejectionReason { get; set; }

    public virtual User ApprovalByNavigation { get; set; }

    public virtual User AssignToNavigation { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<DisposalNote> DisposalNotes { get; set; } = new List<DisposalNote>();

    public virtual ICollection<DisposalRequestDetail> DisposalRequestDetails { get; set; } = new List<DisposalRequestDetail>();
}