// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class DisposalNoteDetail
{
    public Guid DisposalNoteDetailId { get; set; }

    public Guid? DisposalNoteId { get; set; }

    public int? GoodsId { get; set; }

    public int? GoodsPackingId { get; set; }

    public int? PackageQuantity { get; set; }

    public int? Status { get; set; }

    public string Note { get; set; }

    public string RejectionReason { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual DisposalNote DisposalNote { get; set; }

    public virtual Good Goods { get; set; }

    public virtual GoodsPacking GoodsPacking { get; set; }

    public virtual ICollection<PickAllocation> PickAllocations { get; set; } = new List<PickAllocation>();
}