// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class DisposalNote
{
    public Guid DisposalNoteId { get; set; }

    public int? Status { get; set; }

    public int? ApprovalBy { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public Guid DisposalRequestId { get; set; }

    public virtual User ApprovalByNavigation { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<DisposalNoteDetail> DisposalNoteDetails { get; set; } = new List<DisposalNoteDetail>();

    public virtual DisposalRequest DisposalRequest { get; set; }
}