// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class GoodsIssueNoteDetail
{
    public Guid GoodsIssueNoteDetailId { get; set; }

    public Guid? GoodsIssueNoteId { get; set; }

    public int? GoodsId { get; set; }

    public int? Quantity { get; set; }

    public virtual Good Goods { get; set; }

    public virtual GoodsIssueNote GoodsIssueNote { get; set; }
}