// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class GoodsPacking
{
    public int GoodsPackingId { get; set; }

    public int? GoodsId { get; set; }

    public int? UnitPerPackage { get; set; }

    public int? Status { get; set; }

    public virtual ICollection<BackOrder> BackOrders { get; set; } = new List<BackOrder>();

    public virtual ICollection<DisposalNoteDetail> DisposalNoteDetails { get; set; } = new List<DisposalNoteDetail>();

    public virtual ICollection<DisposalRequestDetail> DisposalRequestDetails { get; set; } = new List<DisposalRequestDetail>();

    public virtual Good Goods { get; set; }

    public virtual ICollection<GoodsIssueNoteDetail> GoodsIssueNoteDetails { get; set; } = new List<GoodsIssueNoteDetail>();

    public virtual ICollection<GoodsReceiptNoteDetail> GoodsReceiptNoteDetails { get; set; } = new List<GoodsReceiptNoteDetail>();

    public virtual ICollection<Pallet> Pallets { get; set; } = new List<Pallet>();

    public virtual ICollection<PurchaseOderDetail> PurchaseOderDetails { get; set; } = new List<PurchaseOderDetail>();

    public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; } = new List<SalesOrderDetail>();
}