// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class GoodsIssueNote
{
    public string GoodsIssueNoteId { get; set; }

    public int? Status { get; set; }

    public int? ApprovalBy { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string SalesOderId { get; set; }

    public virtual User ApprovalByNavigation { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<GoodsIssueNoteDetail> GoodsIssueNoteDetails { get; set; } = new List<GoodsIssueNoteDetail>();

    public virtual SalesOrder SalesOder { get; set; }
}