// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class Good
{
    public int GoodsId { get; set; }

    public string GoodsCode { get; set; }

    public string GoodsName { get; set; }

    public int CategoryId { get; set; }

    public int? SupplierId { get; set; }

    public int? StorageConditionId { get; set; }

    public int? UnitMeasureId { get; set; }

    public DateTime? UpdateAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? Status { get; set; }

    public virtual ICollection<BackOrder> BackOrders { get; set; } = new List<BackOrder>();

    public virtual ICollection<Batch> Batches { get; set; } = new List<Batch>();

    public virtual Category Category { get; set; }

    public virtual ICollection<GoodsIssueNoteDetail> GoodsIssueNoteDetails { get; set; } = new List<GoodsIssueNoteDetail>();

    public virtual ICollection<GoodsReceiptNoteDetail> GoodsReceiptNoteDetails { get; set; } = new List<GoodsReceiptNoteDetail>();

    public virtual ICollection<PurchaseOderDetail> PurchaseOderDetails { get; set; } = new List<PurchaseOderDetail>();

    public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; } = new List<SalesOrderDetail>();

    public virtual StorageCondition StorageCondition { get; set; }

    public virtual Supplier Supplier { get; set; }

    public virtual UnitMeasure UnitMeasure { get; set; }
}