// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class GoodsReceiptNoteDetail
{
    public Guid GoodsReceiptNoteDetailId { get; set; }

    public Guid GoodsReceiptNoteId { get; set; }

    public int GoodsId { get; set; }

    public string GoodsPackingId { get; set; }

    public int? ExpectedPackageQuantity { get; set; }

    public int? DeliveredPackageQuantity { get; set; }

    public int? RejectPackageQuantity { get; set; }

    public int? ActualPackageQuantity { get; set; }

    public int? Status { get; set; }

    public string Note { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Good Goods { get; set; }

    public virtual GoodsReceiptNote GoodsReceiptNote { get; set; }
}