// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class GoodsReceiptNote
{
    public string GoodsReceiptNoteId { get; set; }

    public int? Status { get; set; }

    public int? ApprovalBy { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string PurchaseOderId { get; set; }

    public virtual User ApprovalByNavigation { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<GoodsReceiptNoteDetail> GoodsReceiptNoteDetails { get; set; } = new List<GoodsReceiptNoteDetail>();

    public virtual ICollection<Pallet> Pallets { get; set; } = new List<Pallet>();

    public virtual PurchaseOrder PurchaseOder { get; set; }
}