// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class InventoryLedger
{
    public int LedgerId { get; set; }

    public int GoodsId { get; set; }

    public int GoodPackingId { get; set; }

    public DateTime? EventDate { get; set; }

    public int? InQty { get; set; }

    public int? OutQty { get; set; }

    public int? BalanceAfter { get; set; }

    public string Note { get; set; }

    public virtual GoodsPacking GoodPacking { get; set; }

    public virtual Good Goods { get; set; }
}