// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class Location
{
    public int LocationId { get; set; }

    public int? AreaId { get; set; }

    public string LocationCode { get; set; }

    public string Rack { get; set; }

    public int? Row { get; set; }

    public int? Column { get; set; }

    public bool? IsAvailable { get; set; }

    public int? Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual Area Area { get; set; }

    public virtual ICollection<Pallet> Pallets { get; set; } = new List<Pallet>();

    public virtual ICollection<StocktakingLocation> StocktakingLocations { get; set; } = new List<StocktakingLocation>();
}