// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class Pallet
{
    public Guid PalletId { get; set; }

    public Guid? GoodsReceiptNoteId { get; set; }

    public int? PackageQuantity { get; set; }

    public int? UnitsPerPackage { get; set; }

    public int? CreateBy { get; set; }

    public Guid? BatchId { get; set; }

    public int? LocationId { get; set; }

    public int? Status { get; set; }

    public DateTime? CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual Batch Batch { get; set; }

    public virtual User CreateByNavigation { get; set; }

    public virtual GoodsReceiptNote GoodsReceiptNote { get; set; }

    public virtual Location Location { get; set; }

    public virtual ICollection<StocktakingPallet> StocktakingPallets { get; set; } = new List<StocktakingPallet>();
}