// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class PickAllocation
{
    public int PickAllocationId { get; set; }

    public Guid? GoodsIssueNoteDetailId { get; set; }

    public string PalletId { get; set; }

    public int? PackageQuantity { get; set; }

    public int? Status { get; set; }

    public virtual GoodsIssueNoteDetail GoodsIssueNoteDetail { get; set; }

    public virtual Pallet Pallet { get; set; }
}