// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class PurchaseOderDetail
{
    public int PurchaseOrderDetailId { get; set; }

    public string PurchaseOderId { get; set; }

    public int GoodsId { get; set; }

    public int? GoodsPackingId { get; set; }

    public int? PackageQuantity { get; set; }

    public virtual Good Goods { get; set; }

    public virtual GoodsPacking GoodsPacking { get; set; }

    public virtual PurchaseOrder PurchaseOder { get; set; }
}