// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class RefreshToken
{
    public int RefreshTokenId { get; set; }

    public int? UserId { get; set; }

    public string Token { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public bool? IsRevoked { get; set; }

    public DateTime? CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual User User { get; set; }
}