// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class SalesOrder
{
    public Guid SalesOrderId { get; set; }

    public int? RetailerId { get; set; }

    public DateOnly? EstimatedTimeDeparture { get; set; }

    public int? Status { get; set; }

    public int? CreatedBy { get; set; }

    public int? ApprovalBy { get; set; }

    public int? AcknowledgedBy { get; set; }

    public int? AssignTo { get; set; }

    public DateTime? UpdateAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string Note { get; set; }

    public string RejectionReason { get; set; }

    public virtual User AcknowledgedByNavigation { get; set; }

    public virtual User ApprovalByNavigation { get; set; }

    public virtual User AssignToNavigation { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<GoodsIssueNote> GoodsIssueNotes { get; set; } = new List<GoodsIssueNote>();

    public virtual Retailer Retailer { get; set; }

    public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; } = new List<SalesOrderDetail>();
}