// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class SalesOrderDetail
{
    public int SalesOrderDetailId { get; set; }

    public Guid? SalesOrderId { get; set; }

    public int? GoodsId { get; set; }

    public int? Quantity { get; set; }

    public virtual Good Goods { get; set; }

    public virtual SalesOrder SalesOrder { get; set; }
}