// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class StocktakingArea
{
    public Guid StocktakingAreaId { get; set; }

    public string StocktakingSheetId { get; set; }

    public int? AreaId { get; set; }

    public int? AssignTo { get; set; }

    public int? Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual Area Area { get; set; }

    public virtual User AssignToNavigation { get; set; }

    public virtual ICollection<StocktakingLocation> StocktakingLocations { get; set; } = new List<StocktakingLocation>();

    public virtual StocktakingSheet StocktakingSheet { get; set; }
}