// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class StocktakingSheet
{
    public Guid StocktakingSheetId { get; set; }

    public int? Status { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? CreatedBy { get; set; }

    public string Note { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<StocktakingArea> StocktakingAreas { get; set; } = new List<StocktakingArea>();
}