// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class StocktakingLocation
{
    public Guid StocktakingLocationId { get; set; }

    public Guid? StocktakingAreaId { get; set; }

    public int? LocationId { get; set; }

    public string Note { get; set; }

    public int? Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual Location Location { get; set; }

    public virtual StocktakingArea StocktakingArea { get; set; }

    public virtual ICollection<StocktakingPallet> StocktakingPallets { get; set; } = new List<StocktakingPallet>();
}