// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class StocktakingPallet
{
    public Guid StocktakingPalletId { get; set; }

    public Guid? StocktakingLocationId { get; set; }

    public Guid? PalletId { get; set; }

    public int? ExpectedPackageQuantity { get; set; }

    public int? ActualPackageQuantity { get; set; }

    public int? Status { get; set; }

    public string Note { get; set; }

    public DateTime? UpdateAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Pallet Pallet { get; set; }

    public virtual StocktakingLocation StocktakingLocation { get; set; }
}