// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class StorageCondition
{
    public int StorageConditionId { get; set; }

    public decimal? TemperatureMin { get; set; }

    public decimal? TemperatureMax { get; set; }

    public decimal? HumidityMin { get; set; }

    public decimal? HumidityMax { get; set; }

    public string LightLevel { get; set; }

    public int? Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual ICollection<Area> Areas { get; set; } = new List<Area>();

    public virtual ICollection<Good> Goods { get; set; } = new List<Good>();
}