// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class Supplier
{
    public int SupplierId { get; set; }

    public string CompanyName { get; set; }

    public string BrandName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string TaxCode { get; set; }

    public string Address { get; set; }

    public int? Status { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Good> Goods { get; set; } = new List<Good>();

    public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; } = new List<PurchaseOrder>();
}