// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkDistributionWarehouse.Models.Entities;

public partial class User
{
    public int UserId { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string FullName { get; set; }

    public DateOnly? DoB { get; set; }

    public bool? Gender { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public int? Status { get; set; }

    public bool? IsFirstLogin { get; set; }

    public DateTime? CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual ICollection<BackOrder> BackOrders { get; set; } = new List<BackOrder>();

    public virtual ICollection<Batch> Batches { get; set; } = new List<Batch>();

    public virtual ICollection<GoodsIssueNote> GoodsIssueNotes { get; set; } = new List<GoodsIssueNote>();

    public virtual ICollection<GoodsReceiptNote> GoodsReceiptNoteApprovalByNavigations { get; set; } = new List<GoodsReceiptNote>();

    public virtual ICollection<GoodsReceiptNote> GoodsReceiptNoteCreatedByNavigations { get; set; } = new List<GoodsReceiptNote>();

    public virtual ICollection<Notification> NotificationReceivedByNavigations { get; set; } = new List<Notification>();

    public virtual ICollection<Notification> NotificationSendByNavigations { get; set; } = new List<Notification>();

    public virtual ICollection<Pallet> Pallets { get; set; } = new List<Pallet>();

    public virtual ICollection<PurchaseOrder> PurchaseOrderApprovalByNavigations { get; set; } = new List<PurchaseOrder>();

    public virtual ICollection<PurchaseOrder> PurchaseOrderArrivalConfirmedByNavigations { get; set; } = new List<PurchaseOrder>();

    public virtual ICollection<PurchaseOrder> PurchaseOrderAssignToNavigations { get; set; } = new List<PurchaseOrder>();

    public virtual ICollection<PurchaseOrder> PurchaseOrderCreatedByNavigations { get; set; } = new List<PurchaseOrder>();

    public virtual RefreshToken RefreshToken { get; set; }

    public virtual ICollection<SalesOrder> SalesOrderAcknowledgedByNavigations { get; set; } = new List<SalesOrder>();

    public virtual ICollection<SalesOrder> SalesOrderApprovalByNavigations { get; set; } = new List<SalesOrder>();

    public virtual ICollection<SalesOrder> SalesOrderAssignToNavigations { get; set; } = new List<SalesOrder>();

    public virtual ICollection<SalesOrder> SalesOrderCreatedByNavigations { get; set; } = new List<SalesOrder>();

    public virtual ICollection<StocktakingArea> StocktakingAreas { get; set; } = new List<StocktakingArea>();

    public virtual ICollection<StocktakingSheet> StocktakingSheets { get; set; } = new List<StocktakingSheet>();

    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();
}